name: push_app
description: X 푸시 번역기 (내 폰 전용)
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.1
  permission_handler_android: ^13.0.1
  scrollable_positioned_list: ^0.3.5

flutter:
  uses-material-design: true